/* global process, URL, Buffer, localStorage, document, innerWidth, console */
import { createRequire } from 'node:module'
import { readFileSync, mkdirSync } from 'node:fs'
import ts from 'typescript'
import assert from 'node:assert/strict'

// Set PLAYWRIGHT_PACKAGE to a bundled installation, or install playwright locally.
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_PACKAGE || 'playwright')
const seedSource = ts.transpileModule(readFileSync(new URL('../src/seed.ts', import.meta.url), 'utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext } }).outputText
const { seedLaunches } = await import(`data:text/javascript;base64,${Buffer.from(seedSource).toString('base64')}`)
const browser = await chromium.launch({ headless: true, channel: process.env.TEST_BROWSER || 'msedge' })
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } })
const page = await context.newPage()
const errors = []
page.on('pageerror', error => errors.push(error.message))
const url = process.env.TEST_URL || 'http://127.0.0.1:5173'
mkdirSync('artifacts', { recursive: true })
try {
  await page.goto(url)
  await page.getByText('No fully validated comparison yet').first().waitFor()
  assert.equal(await page.getByText('NaN', { exact: true }).count(), 0)
  await page.evaluate(data => localStorage.setItem('apexflite-launches-v1', JSON.stringify(data)), seedLaunches)
  await page.reload()
  await page.getByText('Lowest held-out error:', { exact: false }).first().waitFor()
  const firstRange = page.getByRole('group', { name: 'Mass range zoom' }).first()
  await firstRange.getByRole('spinbutton', { name: 'Minimum visible mass' }).fill('574')
  await firstRange.getByRole('spinbutton', { name: 'Minimum visible mass' }).press('Tab')
  assert.ok((await firstRange.innerText()).includes('6 of 8'))
  const upper = firstRange.getByRole('slider', { name: 'Upper mass handle' })
  await upper.focus(); await upper.press('ArrowLeft')
  assert.ok(Number(await upper.inputValue()) < 602)
  await firstRange.getByRole('button', { name: 'Reset zoom' }).click()
  assert.equal(await firstRange.getByRole('spinbutton', { name: 'Minimum visible mass' }).inputValue(), '560')
  // Pointer drag: exercises native handle hit targets, not just value assignment.
  const lower = firstRange.getByRole('slider', { name: 'Lower mass handle' })
  const rect = await lower.boundingBox()
  await page.mouse.move(rect.x + 14, rect.y + rect.height / 2)
  await page.mouse.down(); await page.mouse.move(rect.x + rect.width * .3, rect.y + rect.height / 2, { steps: 8 }); await page.mouse.up()
  assert.ok(Number(await lower.inputValue()) > 560)
  await firstRange.getByRole('button', { name: 'Reset zoom' }).click()
  const lab = page.locator('.prediction-lab')
  await lab.getByLabel('Descent algorithm').selectOption('neural')
  await page.getByText('The neural network needs 24 valid flights to train.').waitFor()
  await lab.getByLabel('Descent algorithm').selectOption('physics')
  await lab.getByRole('spinbutton', { name: 'Rocket mass', exact: true }).fill('2000')
  await lab.getByText('Outside logged coverage:', { exact: false }).waitFor()
  await lab.getByRole('spinbutton', { name: 'Rocket mass', exact: true }).fill('578')
  await page.screenshot({ path: 'artifacts/overview-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: /Metric/ }).click()
  await page.getByRole('button', { name: 'Overview', exact: true }).click()
  await lab.getByRole('spinbutton', { name: 'Descent altitude' }).waitFor()
  assert.equal(await lab.getByRole('spinbutton', { name: 'Descent altitude' }).inputValue(), '243.84')
  await page.getByRole('button', { name: 'Log a flight', exact: true }).click()
  const modal = page.locator('.modal')
  const altitude = modal.getByLabel('Peak altitude')
  assert.equal(await altitude.inputValue(), '243.84')
  await altitude.fill('250')
  await modal.getByLabel('Total flight time').fill('48')
  await modal.getByLabel('Descent time').fill('35')
  await modal.getByLabel('Parachute size').fill('45.72')
  await modal.getByRole('button', { name: 'Save flight' }).click()
  await modal.waitFor({ state: 'hidden' })
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('apexflite-launches-v1')).at(-1))
  assert.ok(Math.abs(saved.altitude - 250 / .3048) < 1e-6)
  assert.ok(Math.abs(saved.parachuteSize - 18) < 1e-6)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'artifacts/overview-mobile.png', fullPage: true })
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'mobile page must not overflow horizontally')
  await page.evaluate(() => localStorage.setItem('apexflite-theme-v1', 'dark'))
  await page.reload()
  await page.getByText('Lowest held-out error:', { exact: false }).first().waitFor()
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark')
  await page.screenshot({ path: 'artifacts/overview-mobile-dark.png', fullPage: true })
  await page.evaluate(data => localStorage.setItem('apexflite-launches-v1', JSON.stringify(data)), seedLaunches.map(l => ({ ...l, rocketMass: 578 })))
  await page.reload()
  await page.getByRole('heading', { name: 'Descent sensitivity', exact: true }).waitFor()
  await lab.getByRole('slider', { name: 'Lower mass handle' }).waitFor()
  assert.equal(await lab.getByRole('slider', { name: 'Lower mass handle' }).isDisabled(), true)
  // No edits to a user browser: this entire test uses an isolated context.
  assert.deepEqual(errors, [])
  console.log('Browser checks passed: empty/data states, numeric/keyboard/pointer zoom, model switching, extrapolation, metric save, mobile width, no runtime errors.')
} finally { await browser.close() }
