/* global process, URL, Buffer, localStorage, document, innerWidth, console */
import { createRequire } from 'node:module'
import { readFileSync, mkdirSync } from 'node:fs'
import ts from 'typescript'
import assert from 'node:assert/strict'
import { createServer } from 'vite'

// Set PLAYWRIGHT_PACKAGE to a bundled installation, or install playwright locally.
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_PACKAGE || 'playwright')
const seedSource = ts.transpileModule(readFileSync(new URL('../src/seed.ts', import.meta.url), 'utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext } }).outputText
const { seedLaunches } = await import(`data:text/javascript;base64,${Buffer.from(seedSource).toString('base64')}`)
let url = process.env.TEST_URL || 'http://127.0.0.1:5173'
const devServer = process.env.TEST_URL ? null : await createServer({ server: { host: '127.0.0.1', port: 0 } })
if (devServer) { await devServer.listen(); url = devServer.resolvedUrls?.local[0] ?? url }
const launchOptions = process.env.TEST_BROWSER ? { headless: true, channel: process.env.TEST_BROWSER } : { headless: true }
const browser = await chromium.launch(launchOptions)
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } })
const page = await context.newPage()
const errors = []
page.on('pageerror', error => errors.push(error.message))
const navigate = async name => {
  if ((page.viewportSize()?.width ?? 1440) <= 760) await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('button', { name, exact: true }).click()
}
mkdirSync('artifacts', { recursive: true })
try {
  await page.goto(url)
  assert.equal(await page.locator('.prediction-lab').count(), 0)
  await navigate('Launch Planner')
  await page.getByRole('heading', { name: 'More flights needed' }).waitFor()
  assert.equal(await page.getByText('NaN', { exact: true }).count(), 0)
  await page.evaluate(data => localStorage.setItem('apexflite-launches-v1', JSON.stringify(data)), seedLaunches)
  await page.reload()
  await navigate('Launch Planner')
  await page.getByRole('heading', { name: 'Ideal launch mass' }).waitFor()
  assert.equal(await page.getByRole('spinbutton', { name: 'Temperature', exact: true }).count(), 1)
  const currentMass = page.locator('.planner-mass strong')
  const currentMassBeforeWeather = await currentMass.innerText()
  await page.getByRole('spinbutton', { name: 'Wind', exact: true }).fill('8')
  await page.waitForFunction(before => document.querySelector('.planner-mass strong')?.textContent !== before, currentMassBeforeWeather)
  assert.notEqual(await currentMass.innerText(), currentMassBeforeWeather, 'current v2 mass must react to weather')
  await page.getByRole('heading', { name: 'Descent predictor' }).waitFor()
  assert.match(await page.locator('.descent-result strong').innerText(), /sec$/)
  assert.equal(await page.locator('.method-table tbody tr').count(), 5)
  assert.ok((await page.locator('.planner-comparisons').innerText()).includes('80% MOE'))
  await page.screenshot({ path: 'artifacts/planner-v2-desktop.png', fullPage: true })
  await navigate('Settings')
  await page.getByRole('button', { name: /Legacy v1/ }).click()
  await navigate('Dashboard')
  await page.getByRole('heading', { name: 'Original weather-aware model' }).waitFor()
  const firstRange = page.getByRole('group', { name: 'Mass range zoom' }).first()
  await firstRange.getByRole('spinbutton', { name: 'Minimum visible mass' }).fill('574')
  await firstRange.getByRole('spinbutton', { name: 'Minimum visible mass' }).press('Tab')
  assert.ok((await firstRange.innerText()).includes('6 of 8'))
  const upper = firstRange.getByRole('slider', { name: 'Upper mass handle' })
  await upper.focus(); await upper.press('ArrowLeft')
  assert.ok(Number(await upper.inputValue()) < 602)
  await firstRange.getByRole('button', { name: 'Reset zoom' }).click()
  assert.equal(await firstRange.getByRole('spinbutton', { name: 'Minimum visible mass' }).inputValue(), '560')
  // Pointer drag: exercises native handle hit targets, not just value assignment.
  const lower = firstRange.getByRole('slider', { name: 'Lower mass handle' })
  const rect = await lower.boundingBox()
  await page.mouse.move(rect.x + 14, rect.y + rect.height / 2)
  await page.mouse.down(); await page.mouse.move(rect.x + rect.width * .3, rect.y + rect.height / 2, { steps: 8 }); await page.mouse.up()
  assert.ok(Number(await lower.inputValue()) > 560)
  await firstRange.getByRole('button', { name: 'Reset zoom' }).click()
  const simulator = page.locator('.mass-simulator').first()
  const overviewMass = page.locator('.analysis-card.purple .model-footer strong')
  const massBefore = await overviewMass.innerText()
  await simulator.getByRole('spinbutton', { name: 'WIND', exact: true }).fill('5')
  assert.notEqual(await overviewMass.innerText(), massBefore, 'overview mass must react to weather')
  assert.equal(await overviewMass.innerText(), await simulator.locator('.simulator-result strong').innerText())
  await page.screenshot({ path: 'artifacts/overview-desktop.png', fullPage: true })
  await navigate('Launch Planner')
  const lab = page.locator('.prediction-lab')
  await lab.locator('.lab-comparison-disclosure').first().waitFor()
  const massComparisonDisclosure = lab.locator('.lab-stage-mass .lab-comparison-disclosure')
  await massComparisonDisclosure.locator(':scope > summary').click()
  assert.equal(await lab.getByRole('spinbutton', { name: 'Wind', exact: true }).inputValue(), '5')
  const validationComparison = massComparisonDisclosure.locator('.lab-comparison')
  const validationTable = validationComparison.locator('table').first()
  const scoresBefore = await validationTable.innerText()
  const experimentMass = lab.locator('.lab-mass-result strong').first()
  const experimentBefore = await experimentMass.innerText()
  await lab.getByRole('spinbutton', { name: 'Wind', exact: true }).fill('4')
  assert.notEqual(await experimentMass.innerText(), experimentBefore, 'experimental mass must react to weather')
  assert.equal(await validationTable.innerText(), scoresBefore, 'scenario edits must not change flight-validation scores')
  await lab.getByLabel('Mass algorithm').selectOption('physics')
  const massOnly = await experimentMass.innerText()
  await lab.getByRole('spinbutton', { name: 'Wind', exact: true }).fill('6')
  assert.equal(await experimentMass.innerText(), massOnly)
  await lab.getByText('This algorithm is mass-only', { exact: true }).waitFor()
  await navigate('Dashboard')
  assert.equal(await simulator.getByRole('spinbutton', { name: 'WIND', exact: true }).inputValue(), '6')
  assert.equal(await page.locator('.prediction-lab').count(), 0)
  await navigate('Launch Planner')
  await lab.locator('.lab-comparison-disclosure').first().waitFor()
  await massComparisonDisclosure.locator(':scope > summary').click()
  await lab.getByRole('spinbutton', { name: 'Wind', exact: true }).fill('4')
  const downloadEvent = page.waitForEvent('download')
  await validationComparison.getByRole('button', { name: 'Export validation details' }).click()
  const download = await downloadEvent
  await download.saveAs('artifacts/browser-validation.json')
  const audit = JSON.parse(readFileSync('artifacts/browser-validation.json', 'utf8'))
  assert.equal(audit.units.altitude, 'ft')
  assert.equal(audit.results[0].rows.length, 8)
  assert.ok(audit.results[0].trainingMae < audit.results[0].mae)
  await validationComparison.getByRole('button', { name: 'Original weather regression', exact: true }).click()
  await validationComparison.locator('summary').click()
  await lab.getByText('Sparse regression fit:', { exact: false }).waitFor()
  await validationComparison.locator('summary').click()
  await lab.getByLabel('Mass algorithm').selectOption('ridge')
  await lab.getByLabel('Descent algorithm').selectOption('neural')
  assert.equal(await lab.getByLabel('Descent algorithm').inputValue(), 'neural')
  assert.equal(await lab.locator('.lab-summary').first().locator('strong').first().innerText() === '—', false)
  await lab.getByLabel('Mass algorithm').selectOption('neural')
  assert.notEqual(await experimentMass.innerText(), '—')
  assert.ok((await validationTable.getByRole('row').filter({ hasText: 'Neural network' }).innerText()).includes('8/8'))
  await lab.getByLabel('Mass algorithm').selectOption('ridge')
  await lab.getByLabel('Descent algorithm').selectOption('physics')
  await lab.getByRole('spinbutton', { name: 'Rocket mass', exact: true }).fill('2000')
  await lab.getByText('Outside logged coverage:', { exact: false }).waitFor()
  await lab.getByRole('spinbutton', { name: 'Rocket mass', exact: true }).fill('578')
  await page.screenshot({ path: 'artifacts/experiments-desktop.png', fullPage: true })
  await navigate('Settings')
  await page.getByRole('button', { name: /Metric/ }).click()
  await navigate('Launch Planner')
  await lab.getByRole('spinbutton', { name: 'Descent altitude' }).waitFor()
  assert.equal(await lab.getByRole('spinbutton', { name: 'Descent altitude' }).inputValue(), '243.84')
  await page.getByRole('button', { name: 'Log a flight', exact: true }).click()
  const modal = page.locator('.modal')
  const altitude = modal.getByLabel('Peak altitude')
  assert.equal(await altitude.inputValue(), '243.84')
  await altitude.fill('250')
  await modal.getByLabel('Total flight time').fill('48')
  await modal.getByLabel('Descent time').fill('35')
  await modal.getByLabel('Parachute size').fill('45.72')
  await modal.getByRole('button', { name: 'Save flight' }).click()
  await modal.waitFor({ state: 'hidden' })
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('apexflite-launches-v1')).at(-1))
  assert.ok(Math.abs(saved.altitude - 250 / .3048) < 1e-6)
  assert.ok(Math.abs(saved.parachuteSize - 18) < 1e-6)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'artifacts/overview-mobile.png', fullPage: true })
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'mobile page must not overflow horizontally')
  await page.evaluate(() => localStorage.setItem('apexflite-theme-v1', 'dark'))
  await page.reload()
  await navigate('Launch Planner')
  await lab.locator('.lab-comparison-disclosure').first().waitFor()
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark')
  await page.screenshot({ path: 'artifacts/overview-mobile-dark.png', fullPage: true })
  await page.evaluate(data => localStorage.setItem('apexflite-launches-v1', JSON.stringify(data)), seedLaunches.map(l => ({ ...l, rocketMass: 578 })))
  await page.reload()
  await navigate('Launch Planner')
  await page.getByRole('heading', { name: 'Descent sensitivity', exact: true }).waitFor()
  await lab.getByRole('slider', { name: 'Lower mass handle' }).waitFor()
  assert.equal(await lab.getByRole('slider', { name: 'Lower mass handle' }).isDisabled(), true)
  if (process.env.TEST_REPORTED_FILE) {
    const reported = JSON.parse(readFileSync(process.env.TEST_REPORTED_FILE, 'utf8'))
    await page.evaluate(data => { localStorage.setItem('apexflite-launches-v1', JSON.stringify(data)); localStorage.setItem('apexflite-prefs-v1', 'imperial') }, reported)
    await page.setViewportSize({ width: 1440, height: 1100 })
    await page.reload(); await navigate('Launch Planner')
    await massComparisonDisclosure.locator(':scope > summary').click()
    await lab.getByLabel('Mass algorithm').selectOption('baseline')
    const row = validationTable.getByRole('row').filter({ hasText: 'Original weather regression' })
    assert.ok((await row.innerText()).includes('449.10'))
    assert.ok((await row.innerText()).includes('6.23'))
    assert.ok((await row.innerText()).includes('-67.51'))
    await validationComparison.locator('summary').click()
    await page.screenshot({ path: 'artifacts/reported-error-audit.png', fullPage: true })
    await validationComparison.getByText('1752.27', { exact: true }).waitFor()
    await lab.getByLabel('Descent algorithm').selectOption('neural')
    await lab.getByLabel('Mass algorithm').selectOption('neural')
    const neuralRow = validationTable.getByRole('row').filter({ hasText: 'Neural network' })
    assert.ok((await neuralRow.innerText()).includes('8/8'))
    for (const [label, value] of [['Rocket mass', '541.3'], ['Wind', '1.5'], ['Station pressure', '30.125'], ['Humidity', '89'], ['Temperature', '60']]) await lab.getByRole('spinbutton', { name: label, exact: true }).fill(value)
    assert.notEqual(await experimentMass.innerText(), '—')
    assert.notEqual(await lab.locator('.lab-summary').first().locator('strong').first().innerText(), '—')
    await page.screenshot({ path: 'artifacts/neural-eight-flights.png', fullPage: true })
  }
  // No edits to a user browser: this entire test uses an isolated context.
  assert.deepEqual(errors, [])
  console.log('Browser checks passed: separate tab, shared weather, live mass updates, stable validation scores, exported audit, zoom, metric save, mobile/dark layout, constant mass, no runtime errors.')
} finally { await browser.close(); await devServer?.close() }
