import { useMemo, useState } from 'react'
import { NextFlight } from './NextFlight'
import { CartesianGrid, ComposedChart, ReferenceLine, ResponsiveContainer, Scatter, Tooltip, XAxis, YAxis } from 'recharts'
import { flightInsights } from './flightInsights'
import { analysisEngine } from './analysisEngine'
import type { FlightRecord, Units } from './predictionTypes'
import type { DescentConditions } from './analytics'

type Props = { launches: FlightRecord[]; targetAltitude: number; units: Units; conditions: DescentConditions; onPlanner: () => void; onNew: () => void; limits: [number, number] }
const names = { windSpeed: 'Wind', airPressure: 'Air pressure', humidity: 'Humidity', temperature: 'Temperature' }
const number = (v: number, digits = 1) => v.toLocaleString('en-US', { maximumFractionDigits: digits })
const r = (value: number | null) => value === null ? 'Not enough variation' : value.toFixed(2)

export function FlightAnalysis({ launches, targetAltitude, units, conditions, onPlanner, onNew, limits }: Props) {
  const data = useMemo(() => flightInsights(launches), [launches])
  const result = useMemo(() => analysisEngine.recommend(launches, targetAltitude, conditions), [launches, targetAltitude, conditions])
  const [factor, setFactor] = useState<keyof typeof names>('windSpeed')
  const metric = units === 'metric', heightScale = metric ? .3048 : 1, heightUnit = metric ? 'm' : 'ft'
  const windScale = metric ? 1.60934 : 1, windUnit = metric ? 'km/h' : 'mph'
  const height = (v: number) => `${number(v * heightScale)} ${heightUnit}`
  const selected = result.comparisons.find(c => c.selected)
  const baseline = result.comparisons.find(c => c.method === 'monotonic-baseline')
  const wind = data.factors[0]
  const xUnit = factor === 'windSpeed' ? windUnit : factor === 'temperature' ? (metric ? '°C' : '°F') : factor === 'airPressure' ? (metric ? 'hPa' : 'inHg') : '%'
  const xValue = (f: FlightRecord) => factor === 'windSpeed' ? f.windSpeed * windScale : factor === 'temperature' && metric ? (f.temperature - 32) * 5 / 9 : factor === 'airPressure' && metric ? f.airPressure * 33.8639 : f[factor]
  return <>
    <section className="page-heading"><div><p className="eyebrow">WIND · MASS · FLIGHT PATH</p><h1>Flight insights</h1><p className="subtitle">Separate measured patterns from what still needs more flights.</p></div><button className="primary-button" onClick={onNew}>Log a flight</button></section>
    <section className="flight-analysis">
      <NextFlight flights={launches} targetAltitude={targetAltitude} units={units} limits={limits} />
      <div className="evidence-summary"><div><span>Flight evidence</span><strong>{data.flights.length} flights · {data.days} days</strong></div><div><span>Logged wind</span><strong>{wind.min === null ? '—' : `${number(wind.min * windScale)}–${number(wind.max! * windScale)} ${windUnit}`}</strong></div><div><span>Held-out altitude error</span><strong>{selected?.metrics ? height(selected.metrics.mae) : 'Needs more launch days'}</strong></div><div><span>Observed tilt recorded</span><strong>{data.tiltCount} / {data.flights.length} flights</strong></div></div>
      {!data.flights.length ? <article className="planner-card"><h2>Start with your flight log</h2><p>Import your workspace in Flights or log a flight to explore wind, mass and altitude together.</p></article> : <>
        <div className="evidence-grid"><article className="planner-card"><p className="eyebrow">WHAT THE LOG SUPPORTS</p><h2>Wind, after accounting for mass</h2><p>Raw wind–altitude correlation: <b>{r(wind.raw)}</b>. After accounting for inverse mass: <b>{r(wind.adjusted)}</b>.</p><p>{wind.adjusted === null ? 'More variation is needed to estimate the wind relationship.' : Math.abs(wind.adjusted) < .3 ? 'The remaining wind association is weak in this log.' : `Higher wind is associated with ${wind.adjusted < 0 ? 'lower' : 'higher'} altitude after the mass adjustment.`} This is an association, not proof of a wind effect.</p><p className="field-help">{data.days} launch days are the independent validation groups. Mass adjustment does not remove motor, flight-path or launch-day differences.</p></article>
        <article className="planner-card"><p className="eyebrow">WHAT TO RECORD NEXT</p><h2>Make tilt measurable</h2><p>{data.tiltCount === 0 ? 'No flights record observed tilt yet. We cannot tell whether tilt explains the remaining variation.' : `${data.tiltCount} flights record tilt. These observations are not yet used as prediction coefficients.`}</p><p>Repeat a familiar mass and configuration. Record wind at launch and whether the powered flight stayed straight or tilted. No angle measurement is needed. Use the same observation method each time.</p><p className="field-help">Keep launch setup consistent when comparing wind. Do not change angle just to chase an altitude prediction.</p></article></div>
        <article className="planner-card"><div className="evidence-heading"><div><p className="eyebrow">CONDITION EXPLORER</p><h2>Altitude remaining after mass adjustment</h2></div><label>Compare condition<select aria-label="Analysis condition" value={factor} onChange={e => setFactor(e.target.value as keyof typeof names)}>{Object.entries(names).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div><div className="lab-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data.residuals.map(({ flight, residual }) => ({ x: xValue(flight), y: residual * heightScale, date: flight.date }))} margin={{ top: 10, right: 25, left: 0, bottom: 15 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="x" type="number" unit={` ${xUnit}`} /><YAxis dataKey="y" unit={` ${heightUnit}`} /><Tooltip formatter={(v, name) => [number(Number(v)), name === 'x' ? `${names[factor]} (${xUnit})` : `Altitude residual (${heightUnit})`]} /><ReferenceLine y={0} stroke="#8994aa" /><Scatter dataKey="y" fill="#7758d8" /></ComposedChart></ResponsiveContainer></div><div className="method-table-wrap"><table className="method-table"><thead><tr><th>Variable</th><th>Raw correlation</th><th>Mass-adjusted correlation</th><th>Prediction priority</th></tr></thead><tbody>{data.factors.map(f => <tr key={f.key}><th>{names[f.key]}</th><td>{r(f.raw)}</td><td>{r(f.adjusted)}</td><td>{f.key === 'windSpeed' ? 'Primary candidate with mass' : 'Strongly reduced / optional'}</td></tr>)}</tbody></table></div><p className="field-help">Correlation r ranges from −1 to +1; it is not a percentage of causal importance. Pressure, humidity and temperature may track the same launch days. In this analysis experiment their coefficients are strongly shrunk, and excluded entirely by the mass + wind model. Production predictions are unchanged.</p></article>
        <div className="evidence-grid"><article className="planner-card"><h2>Comparable flights</h2><p>Same launch day, masses within 5 g, wind difference at least {number(.5 * windScale)} {windUnit}. Pairs can share flights and are not independent experiments.</p>{data.pairs.length ? <div className="comparison-pairs">{data.pairs.slice(0, 5).map(p => <div key={`${p.first.id}-${p.second.id}`}><b>{p.first.date}</b><span>Wind +{number(p.windDelta * windScale)} {windUnit} · mass {p.massDelta >= 0 ? '+' : ''}{number(p.massDelta)} g</span><strong>Altitude {p.altitudeDelta >= 0 ? '+' : ''}{height(p.altitudeDelta)}</strong></div>)}</div> : <p>No close comparisons yet. Repeated configurations will make wind comparisons more useful.</p>}</article>
        <article className="planner-card"><h2>Experimental model comparison</h2><p>{selected ? `${selected.methodLabel} leads this analysis comparison for the entered conditions.` : 'More varied flights are needed before selecting a model.'}</p>{selected?.metrics && <p>Leaving each launch day out gives a mean absolute miss of <b>{height(selected.metrics.mae)}</b> over {selected.metrics.testedFlights} flights.{baseline?.metrics && ` Mass-only comparison: ${height(baseline.metrics.mae)}.`}</p>}<p>This analysis experiment gives mass and wind first consideration, and keeps atmospheric corrections small. A simpler mass model can win if wind adds little predictive value.</p><button className="secondary-button" onClick={onPlanner}>Open production planner</button><p className="field-help">Production predictions are unchanged. These same held-out scores also select the experimental model, so they are a comparison estimate, not an independent final accuracy guarantee.</p></article></div>
        {data.sameTimes > 0 && <article className="planner-card"><h2>Timing records to check</h2><p>{data.sameTimes} flights have identical total flight and descent times. If these are total flight times, record the descent segment separately before relying on recovery predictions.</p></article>}
      </>}
    </section>
  </>
}
