import { useMemo, useState } from 'react'
import { compareFlights, recommendNextFlight } from './dayRecommendation'
import type { FlightRecord, Units } from './predictionTypes'

const localDate = () => { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}` }
const n = (value: number) => value.toLocaleString('en-US', { maximumFractionDigits: 1 })
export function NextFlight({ flights, targetAltitude, units, limits }: { flights: FlightRecord[]; targetAltitude: number; units: Units; limits: [number, number] }) {
  const [date, setDate] = useState(localDate)
  const [wind, setWind] = useState<number | null>(null)
  const [observations, setObservations] = useState<Record<string, FlightRecord['observedTilt']>>({})
  const [firstId, setFirstId] = useState('')
  const [secondId, setSecondId] = useState('')
  const [latestId, setLatestId] = useState('')
  const annotated = useMemo(() => flights.map(f => Object.hasOwn(observations, f.id) ? { ...f, observedTilt: observations[f.id] } : f), [flights, observations])
  const chronological = [...annotated].sort((a, b) => a.date.localeCompare(b.date))
  const recent = chronological.filter(f => f.date <= date).at(-1)
  const expectedWind = wind ?? recent?.windSpeed ?? 0
  const result = recommendNextFlight(annotated, date, targetAltitude, expectedWind, limits, latestId)
  const first = annotated.find(f => f.id === firstId) ?? chronological.at(-2)
  const second = annotated.find(f => f.id === secondId) ?? chronological.at(-1)
  const comparison = first && second && first.id !== second.id ? compareFlights(annotated, first, second) : null
  const metric = units === 'metric', heightScale = metric ? .3048 : 1, windScale = metric ? 1.60934 : 1
  const height = (value: number) => `${n(value * heightScale)} ${metric ? 'm' : 'ft'}`
  const label = (f: FlightRecord) => `${f.date} · ${n(f.rocketMass)} g · ${height(f.altitude)}`
  const tiltInput = (flight: FlightRecord) => <label>Flight path for {label(flight)}<select aria-label={`Flight path ${flight.id}`} value={flight.observedTilt ?? ''} onChange={e => setObservations(current => ({ ...current, [flight.id]: (e.target.value || null) as FlightRecord['observedTilt'] }))}><option value="">Unknown</option><option value="straight">Straight</option><option value="slight">Slight tilt</option><option value="strong">Noticeable tilt</option></select></label>
  return <>
    <article className="planner-card next-flight"><p className="eyebrow">ANALYSIS EXPERIMENT · PRODUCTION MODEL UNCHANGED</p><h2>Next flight mass</h2><p>Target {height(targetAltitude)}. Start with history, then adapt to flights logged on the selected day. A shared date does not guarantee unchanged wind or flight path.</p>
      <div className="tilt-controls"><label>Launch day<input aria-label="Recommendation launch day" type="date" value={date} onChange={e => setDate(e.target.value)} /></label><label>Expected wind ({metric ? 'km/h' : 'mph'})<input aria-label="Next flight wind" type="number" min="0" step="0.1" value={n(expectedWind * windScale).replaceAll(',', '')} onChange={e => setWind(e.target.value === '' ? null : e.target.valueAsNumber / windScale)} /></label></div>
      {annotated.some(f => f.date === date) && <div className="tilt-controls"><label>Previous flight<select aria-label="Previous flight" value={annotated.some(f => f.date === date && f.id === latestId) ? latestId : ''} onChange={e => setLatestId(e.target.value)}><option value="">Auto: most recently saved on this day</option>{annotated.filter(f => f.date === date).map(f => <option key={f.id} value={f.id}>{label(f)}</option>)}</select></label></div>}
      {result.status === 'ready' ? <div aria-live="polite"><div className="planner-mass"><strong>{n(result.mass)}</strong><span>g total launch mass</span></div><p><b>{result.repeat ? `Repeat this mass for ${result.repeatsRemaining} more comparable flight${result.repeatsRemaining === 1 ? '' : 's'}.` : result.dayFlights === 0 ? 'Start with 3 repeat flights at this mass.' : 'Try one flight, then recalculate.'}</b></p><p>{result.method} · {result.dayFlights} same-day flights · {result.bracket ? 'Direct same-day interpolation' : `${Math.round(result.dayShare * 100)}% same-day offset weight`}.</p><p>Expected altitude {height(result.expected)}; historical residual spread about ±{height(result.spread)}. This spread is descriptive, not a guaranteed prediction interval.</p><p>Model target mass: {n(result.desired)} g. {result.repeat ? 'Confirm repeatability before chasing the target.' : 'Each adjustment from the last logged mass is capped at 3 g.'} Mass sensitivity near here: {height(result.slopeAtMass)} per added gram.</p>{result.latest && <div className="tilt-controls">{tiltInput(result.latest)}</div>}<details className="analysis-methods"><summary>How this recommendation works</summary><p className="field-help">Plan for 3 comparable repeats within 1 g and similar wind. The latest same-day flight gets twice the recency weight. Straight / slight / noticeable tilt weights are 1 / 0.5 / 0.15; unknown is 0.7. These are conservative test settings, not learned physics. Noticeable tilt prompts a repeat and has less influence. No invented tilt correction is added.</p>{result.bracket && <p>Interpolation endpoints: {label(result.bracket.a)} and {label(result.bracket.b)}. Both are recorded straight, have winds within 1 mph of each other and the scenario, and bracket the target. With only two endpoints, confirm the result with a repeat.</p>}<p className="field-help">Supported mass: {n(result.low)}–{n(result.high)} g. The most recently added record on this date is treated as the latest flight. The target and mass limits come from Settings. Historical views exclude later dates. If the imported order is uncertain, select the previous flight explicitly.</p></details></div> : <p role="status">{result.reason}</p>}
    </article>
    <article className="planner-card"><p className="eyebrow">FLIGHT-PATH INVESTIGATION</p><h2>How much altitude remains unexplained?</h2><p>Compare two flights. Account for their mass difference using the other flights, then inspect what remains. Wind, tilt, motor variation and measurement error can all be mixed into this difference.</p><div className="tilt-controls"><label>Reference flight<select aria-label="Reference flight" value={first?.id ?? ''} onChange={e => setFirstId(e.target.value)}>{chronological.map(f => <option key={f.id} value={f.id}>{label(f)}</option>)}</select></label><label>Comparison flight<select aria-label="Comparison flight" value={second?.id ?? ''} onChange={e => setSecondId(e.target.value)}>{chronological.map(f => <option key={f.id} value={f.id}>{label(f)}</option>)}</select></label>{first && tiltInput(first)}{second && first?.id !== second.id && tiltInput(second)}</div>{comparison && <div className="evidence-summary tilt-results"><div><span>Actual altitude difference</span><strong>{height(comparison.observed)}</strong></div><div><span>Expected from mass alone</span><strong>{comparison.massExpected === null ? 'Insufficient data' : height(comparison.massExpected)}</strong></div><div><span>Unexplained difference</span><strong>{comparison.unexplained === null ? 'Insufficient data' : height(comparison.unexplained)}</strong></div></div>}<p className="field-help">Differences are comparison minus reference. The unexplained part is not a measured tilt penalty. These flight-path selections are temporary what-if observations and affect only this Analysis experiment. To keep an observation, edit the flight in Flights. None of these controls changes the production algorithm.</p></article>
  </>
}
